### ISSUE TITLE
Issue with Hydra

### ISSUE THREAD

**Issue by helpful-sam** [ciampluca/counting_perineuronal_nets#4]
Having cloned the repository and adding a tif image to the root of the repository, and running the command:

python predict.py pnn_fasterrcnn_640/ -r pnn_scoring_rank_learning/ -t 0.0 image.tif`

I get this error:

![image](https://user-images.githubusercontent.com/28850028/215398155-2821446b-73f3-4be6-a249-7010014ffbf7.png)

**Comment by fabiocarrara** [comment]
You are using old models (v0.3) with newer code (v0.5). Our bad: we forgot to update the download links of models in the README.
You can either downgrade the code to the v0.3 tag or download the v0.5 models [here](https://github.com/ciampluca/counting_perineuronal_nets/releases).

**Comment by samleecode** [comment]
Updating the models and re-running the localization worked! However, when attempting to do localization + scoring, I get this error (I have torch 1.7.1 per the requirements):

![image](https://user-images.githubusercontent.com/28850028/215526635-b073602a-9c65-4c1b-bcce-1fb971afaaf1.png)

**Comment by fabiocarrara** [comment]
Thanks for reporting. `torchsort` is missing in `requirements.txt`.
Try installing it via pip:
`pip install torchsort`

**Comment by rsnelson1** [comment]
Thank you very much for your help! I have this error as well and when I install via pip I just this error:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/98787539/215584407-30f9cda3-b57f-46c2-bf88-fe2ff163a6e7.png">

Do you know how I could fix this?

**Comment by helpful-sam** [comment]
Installing torchsort does circumvent this error!
